### PR TITLE
Split run script

### PR DESCRIPTION
**Pull request by dirkmoors**
I've added a extra option next to 'start' and 'live': 'shell' will simply run /bin/bash inside the docker container.

Also I've added an extra folder to .gitignore to exclude PyCharm's cfg folder.

### CODE REVIEW

**Comment by rroemhild** [comment]
I think the EJABBERD_NODENAME get in conflict with https://github.com/rroemhild/docker-ejabberd/blob/master/run#L154-157. I copied this part to the wrong pre-script. It should be left in the run script to get processed on early stage. Or did I miss something?

**Comment by rroemhild** [comment]
I add ERLANG_NODE back to the run-script with the latest commit 0b2abbe5.

**Comment by dirkmoors** [comment]
No EJABBERD_NODENAME is meant to be able to define the part before the '@' via an environment variable (e.g. in the Dockerfile). The part after the '@' will default to the hostname.

**Comment by rroemhild** [comment]
If I'm not getting it wrong erlang adds the hostname to nodename https://github.com/rroemhild/docker-ejabberd/blob/master/ejabberdctl.cfg.tpl#L121-L137

**Comment by dirkmoors** [comment]
You are correct. 

Also I understand that you currently generate a random password, but looking at clustering multiple ejabberd nodes, It might be usefull to be able to define the password with an environment variable (maybe even in the docker file)? That way, all the ejabberd nodes that will be added in the cluster, will have the same password for the admin user.

**Comment by rroemhild** [comment]
Added an envvar to define admin passwords and cherry-picked your commits 615cb3144e5ce75b17bb3ff03523c254d6a0cc1a and 1d2ebc8a25dd88999f77da618b3e2bbda05ca538 to keep the commit log clean, hopefully this is ok for you.

**Comment by dirkmoors** [comment]
Great, thanks!

**Pull request closed without merging**
