### PR TITLE
Add mysql auth type

### PR DESCRIPTION
**Pull request by cdauth**
This pull request adds a new auth type `mysql` that allows to authenticate against a MySQL database. It supports defining custom queries and a hash type to support a wide range of database layouts.

### CODE REVIEW

**Comment by rroemhild** [comment]
Hi, that's a great contribution but I would prefer to add this script on container build from a public repository, so on re-build we have always the latest version.

**Comment by cdauth** [comment]
The way it works with the external auth is that there is a [list of contributions](https://www.ejabberd.im/extauth) in the ejabberd docs, which are links to external websites. None of the scripts there work without further customisation, and many of the links don't even work anymore. I took the Python script because python is already installed in the container, but had to modify it quite a lot, because it didn't support custom hash algorithms, custom table layouts, changing passwords, registering and unregistering, and it even had an SQL injection vulnerability.

So I wrote the script specifically for this pull request. My idea was to add a link to the script in this repository to the list of ejabberd contributions, and if ever any changes are needed, to make them here.

But if you would prefer it to be in an external repository, I can create one for the script and pull it from there in the Dockerfile.

**Comment by rroemhild** [comment]
I would like to see your script in an extra repo and add it from this resource on docker build. You can use ```ADD URL``` in Dockerfile for this. IMO the advantage is that it's simpler for others to find and contribute to your improved script.

**Comment by cdauth** [comment]
Okay, I will create an external repository.

Do you want the documentation of the environment variables to be in the README at all, or should there be just a link to the README of the external repository?

**Comment by rroemhild** [comment]
Keep documentation in README, maybe with a link to your repo. Thx!

**Comment by cdauth** [comment]
I already checked it in, feel free to review and merge.

**Comment by rroemhild** [comment]
Hi, I merged your PR on #76 to keep a more generic way to support external authentication. To use mysql authentication set `EJABBERD_AUTH_METHOD=external` and `EJABBERD_EXTAUTH_PROGRAM=/opt/ejabberd/scripts/lib/auth_mysql.py`.

Thx for your contribution!

**Pull request merged**
