### PR TITLE
Refactored to have the Dockerfile build ejabberd from source

### PR DESCRIPTION
**Pull request by dirkmoors**
I've refactored the Dockerfile (and config files) to completely build ejabberd from source. This allows for having a custom (newer) erlang binary (>=R17) which is needed to be able to install modules like e.g. 'mod_muc_admin'. You'll also notice that ejabberd will be installed in the default directories as specified in https://www.process-one.net/docs/ejabberd/guide_en.html#install to avoid confusion.
Only custom scripts and other resources are copied into $EJABBERD_HOME/bin.

### CODE REVIEW

**Comment by dirkmoors** [comment]
Todo: Make the branch configurable (I'll look into that tomorrow)

**Comment by rroemhild** [comment]
Hi Dirk, I used to install ejabberd from source in the past. But switched to the binary installer with the result for smaller images. I've also thought about going back to compile ejabberd, for newer erlang binary, compiling modules and a new ejabberd feature compiling elixier modules. So thanks for your PR!

I'll test to build the image and merge it later, in the meantime it would be great if you add `--enable-elixir` to configure. And I would keep the naming for `EJABBERD_VERSION` instead of `EJABBERD_BRANCH` I think it is more intuitive and `VERSION` is euqal to `BRANCH`.

**Comment by dirkmoors** [comment]
Hi Rafael, you're welcome! 
I'll add the configuration option you request!
The reasoning behind changing to EJABBERD_BRANCH is that I would like to be able to choose 'master', or even a specific commit hash as the ejabberd 'branch' I'll be building from. In that sense, I would argue that EJABBERD_BRANCH covers the payload more then EJABBERD_VERSION?

**Comment by rroemhild** [comment]
In that sense you're correct and I'm fine with naming EJABBERD_BRANCH.

**Comment by dirkmoors** [comment]
Ready for review and merge

**Comment by rroemhild** [comment]
Looks good. There is no need for X11 or is it? It would save ~130MB image size without X11.

```diff
diff --git a/Dockerfile b/Dockerfile
index e9426ad..c83aedd 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -47,7 +47,12 @@ RUN echo 'deb http://packages.erlang-solutions.com/debian wheezy contrib' >> /et
     && curl --silent --output /tmp/erlang_solutions.asc -L "http://packages.erlang-solutions.com/debian/erlang_solutions.asc" \
     && apt-key add /tmp/erlang_solutions.asc \
     && apt-get update \
-    && apt-get -y --no-install-recommends install erlang \
+    && apt-get -y --no-install-recommends install erlang-base \
+        erlang-snmp erlang-ssl erlang-ssh erlang-webtool erlang-tools \
+        erlang-xmerl erlang-corba erlang-diameter erlang-eldap \
+        erlang-eunit erlang-ic erlang-inviso erlang-odbc erlang-os-mon \
+        erlang-parsetools erlang-percept erlang-typer erlang-src \
+        erlang-dev \
     && rm /tmp/erlang_solutions.asc \
     && rm -rf /var/lib/apt/lists/*
 
@@ -60,6 +65,7 @@ RUN cd /tmp \
     && ./configure --enable-elixir --enable-zlib --enable-nif --enable-user=$EJABBERD_USER \
     && make \
     && make install \
+    && cd $EJABBERD_HOME && rm -rf /tmp/ejabberd
     && chown -R $EJABBERD_USER /etc/ejabberd
 
 # Wrapper for setting config on disk from environment
```

I'm not sure if we need all the erlang packages, I just removed the packages with x11 dependencies.

**Comment by dirkmoors** [comment]
You are correct. I've fixed that in https://github.com/dirkmoors/docker-ejabberd/commit/68ab5573c6d7805d4cc8ee47f13c0f0627b1a0a3 (and also a bug with the locale configuration).

**Comment by rroemhild** [comment]
Just one more thing, I noticed that you installed ejabberd into the system. I like the idea to keep everything ejabberd in `/opt/ejabberd`. And installing i.e the config to `/etc` will break compatibility with other users that use this as base image, with config in `/opt/ejabberd/etc`. Can we just let this in ejabberd's homedir?

```
./configure --prefix=$EJABBERD_HOME --enable-elixir --enable-zlib --enable-nif --enable-user=$EJABBERD_USER
```

**Comment by dirkmoors** [comment]
Yeah the problem with the 'prefix' solution is that it will generate the installed folders as follows:

/opt/ejabberd**/etc/ejabberd/**
/opt/ejabberd**/lib/ejabberd/**
/opt/ejabberd**/sbin/**
/opt/ejabberd**/var/lib/ejabberd/**
/opt/ejabberd**/var/log/ejabberd/**

This is probably not what we want?

**Comment by rroemhild** [comment]
I've looked into this and yes you are right we don't want this directory structure. I'll merge your PR and apply some patches for backwards compatibility.

**Comment by dirkmoors** [comment]
Awesome, I'm looking forward to the merge into master!

**Pull request merged**
