### PR TITLE
Adding optional support for ODBC and/or Redis configuration, and adding module install feature

### PR DESCRIPTION
**Pull request by who**
This adds optional support for ODBC and/or Redis configuration, and allows the user to optionally provide a default database. Also, it gives the ability to alter the ejabberd session storage DB.

Also, this PR includes a new post script which gives the user to optionally install modules. See this isue for more details: https://github.com/rroemhild/docker-ejabberd/issues/84

### CODE REVIEW

**Comment by rroemhild** [comment]
Thx for this PR and that you add redis functionality. I'll review your PR and merge it later.

**Comment by rroemhild** [comment]
Thanks for your contribution!

**Comment by who** [comment]
@rroemhild I discovered a bug with the module loader script in this PR - we should only run this script on first start, so we need to add this to the file:

```
file_exist ${FIRST_START_DONE_FILE} \
    && exit 0
```

I will submit another quick PR for this.

**Comment by vanflymen** [comment]
Is there any readme for this?

**Pull request merged**
