### PR TITLE
Removed entrypoint

### PR DESCRIPTION
**Pull request by dirkmoors**
We should put the start command under CMD only. Otherwise, docker (and/or docker-compose) builtin commands won't work anymore.

### CODE REVIEW

**Comment by rroemhild** [comment]
Can you give me an example for this please. ENTRYPOINT and CMD can be overwritten with docker-compose, but I didn't used it for a while. Removing ENTRYPOINT from the docker-image will change how the live mode can be used from ```docker run -i -t -P rroemhild/ejabberd live``` to ```docker run -i -t -P rroemhild/ejabberd run live```. Not a big change but could confuse some people.

**Comment by dirkmoors** [comment]
Hey,

If we keep using 'ENTRYPOINT'; we cannot do something like:

$ docker-compose run docker-ejabberd env

This would print out all the environment variables.

**Comment by rroemhild** [comment]
I see the point and have a different solution to support the docker-compose run command and keep the ENTRYPOINT in 359a748. For testing committed to the ```commands``` branch.

**Comment by dirkmoors** [comment]
Ok thanks, I'll test it asap, and I'll let you know if it works for me!

**Comment by dirkmoors** [comment]
Fixed: https://github.com/rroemhild/docker-ejabberd/pull/56

**Pull request closed without merging**
